siemens/linux-entra-sso

.github/workflows/deploy-update-manifest.yml
.pages/firefox/updates.json
.pages/firefox/updates.json.license
README.md
platform/firefox/manifest.json

The idea is to deploy the update manifest for Mozilla Firefox to github pages. On new releases, we create the release and build the (unsigned) xpi. Then, we upload that to AMO and wait for it to be signed. Once signed, we download the signed xpi and attach that to the release. Then, we update the update manifest and push that to main (which updates it on gh-pages as well). After that, all Firefox instances that have updates for this extension enabled will automatically download and updatethe extension.
closes: #5

chore: deploy firefox addon via gh-pages

---

background.js
linux-entra-sso.py

This solves the host-part double initialization and non-termination issues on Chrome and Chromium.

Various fixes around the extensions lifecycle on Chrome / Chromium

---

.github/workflows/release.yml

To harden this repo against supply chain attacks, we pin all external actions to full git digests.

ci: pin external gh actions

---

background.js

Before requesting a new API token, we need clear the variable that holds the current one, as this state is used as a synchronization point to wait for the token response.
This fixes issues, where the profile picture could not be loaded, because an outdated token was used.

fix: reset api token before requesting new

---

.github/workflows/release.yml
CONTRIBUTING.md

Previously we automatically committed the update manifest to the main branch after the release was created. This approach had two issues:
- no option to manually inspect xpi file before rollout
- main branch cannot be protected (limited to maintainer-only)
This patch replaces this auto-commit with a pull request based workflow, where the CI action just creates a MR, but this has to be manually merged.

ci: add manual approval step before release of update manifest

---

PRIVACY.md

The privacy statement is needed to publish the extension on the Chrome webstore. It documents with which services the extension interfaces and that the extension itself does not collect any data.

docs: add privacy statement

---

.github/workflows/release.yml
CONTRIBUTING.md
Makefile
README.md
platform/chrome/linux_entra_sso.json
platform/firefox/linux_entra_sso.json

As we finally have the extension published on the Chrome Web Store (unlisted currently), we can also install the host parts globally. By that, a (inhouse) Linux distro can package the host parts and enroll them. Then, the users only need to install the web extension from the browser extension stores.

Add listing on Chrome Web Store and support to package host parts

---

Makefile
README.md
platform/chrome/extension.json
platform/chrome/extension.json.license

By pre-registering the extension on Chrome on install, the browser automatically downloads and installs the latest version of the extension on startup. By that, we can prepare both the host and the browser part for Chrome and ship that as part of the distribution.

feat: pre-register extension on Chrome

---

README.md

The documentation did not mention to get the signed .xpi file form the github releases page. This patch makes this point more clear.
cc @romanho
closes: #18

docs: improve documentation around how to install on FF

---

Makefile
README.md

The native messaging dirs vary across Linux distributions. By that, these dirs need to be configurable. This patch adds this logic, as well as a note about this ambiguity.
closes: #21

chore: make install paths configurable

---

CONTRIBUTING.md

Once the chrome / chromium version of the extension is signed, we need to download it from the store and upload to the releases. As this step is tricky to automate, we just document it for now.
cc @rutgerputter

docs: add note to upload .crx to release, once signed

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile

Just CI and release creation cleanup. No functional changes to any of the extension parts.

Maintenance work

---

linux-entra-sso.py

In case the identity broker is not registered as systemd service, we cannot start it. This however is also not needed, as long as the service is visible on the bus.
This patch changes the logic to check for a running broker by first checking if it is running and only if not starting it.

chore: check if broker is running before starting

---

CONTRIBUTING.md
Makefile
README.md
background.js
linux-entra-sso.py
popup/menu.js

When updating the browser plugin via the app stores, the host version might get out of sync with the web extension version.
To notify the user about this, we add an endpoint (API call) to query version information of the host tooling. In case it does not match we show both versions in the UI. Later on, we can define version boundaries and show a more prominent warning. For now, this is not needed as we are 100% compatible with the first released version.

feat: show plugin versions in menu

---

background.js
linux-entra-sso.py

The broker implements DBus activation. However, it appears on the bus before it can fully be used (i.e. before the `/com/microsoft/identity/broker1` becomes visible). By that, the buffered API calls are dispatched too early and return with an UnknownObject
error. This affects both the introspection and API calls.
To work around this, we poll for the path to show up before performing any other broker communication. Once the broker disappears, we clear our internal state to ensure the polling happens again before the next invocation.
Closes: #33

Workaround for incorrect DBus activation

---

LICENSE

The licensee tool is used by github (and others) to detect the name, version and attribution of a repositories license. In case of github, this data is then shown in the summary page, making it easily available to users. As we did not provide a LICENSE or copying file, but just stated the license in the README.md, the tooling was not able to detect the license with a sufficiently high confidence to show this as MPL-2.0.
We copy the license file from the LICENSES dir to the repo root, as neither licensee nor reuse lint supports symlinks. The change does not change the license itself in any form. It is just about making it accessible to tooling.

chore: make license detectable by licensee

---

.github/workflows/build.yml
.github/workflows/deploy-update-manifest.yml
.github/workflows/release.yml

Not much changes, but splitting the global workflow permissions from the job permissions is best practice.

ci: use fine-grained job-token permissions

---

Makefile

PyGObject is a direct dependency of linux-entra-sso, so we should declare it as a runtime dependency for our Debian package. Previously, we were fortunate that python3-pydbus already depends on python3-gi, which inadvertently fulfilled our dependency.

chore(deb): add python3-gi as explicit dependency

---

.github/workflows/build.yml

Currently we don't run the build workflow on external pull requests. This makes it tricky to detect build and style issues on these requests.
As we already require explicit approval for all external contributors before running the action, it is fine to also enable the workflow. Further, I carefully checked the configuration of the repo with the poutine tool for possible bypasses.

ci: run build workflow on external pull requests

---

.github/workflows/build.yml

When running the build for external PRs, we do not have access to secrets (for good reason). By that, we also cannot perform the attestation step. Just skip it in these cases.
Signed-off-by: Felix Moessbauer <felix.moessbauer@siemens.com>

ci: attest build only on push

---

background.js
linux-entra-sso.py

Fix error handling for acquireTokenSilently and getAccounts according to my understanding of linux-entra-sso.py. 
Note that I only tested the acquireTokenSilently path, but I don't see why getAccounts should behave differently.
Additionally, I fixed an indefinite wait in case avatar API token can't be acquired.

fix error handling for acquireTokenSilently and getAccounts

---

background.js
linux-entra-sso.py
popup/menu.css
popup/menu.html
popup/menu.js

In case the connection to the broker is lost, an indication of that situation should be given to the user. While this is not an error by itself (given that the broker is dbus-activated), it still provides valuable information for debugging. We now indicate this by adding a red circle around the avatar in this case, as well as stating the current status in the menu (when clicking on the icon).
Proposed-by: Jan Kiszka <jan.kiszka@siemens.com>

feat: indicate broker online state in UI

---

Makefile

In case the user does not have a profile picture, a fallback icon is used. This icon was not included in the firefox deployment, hence the loading of that failed and rejecting the promise (waiting for the icon to be come available).
Closes: #59

fix(firefox): include missing profile avatar

---

background.js

In case an error happens between "login" (assignment of the account) and
loading the profile picture, we don't have any profile picture set. This
is problematic as downstream functions require a valid image data
object. To fix this, we load the dummy image upfront and then wait for
the actual image to be available.

Fix internal issues in case of error during avatar loading

---

README.md

Previously we stated that the Snap version of Firefox is not supported. However, this recently changed but requires some additional actions. We now reflect that in the README.

docs: describe prerequisites for Snap Firefox version

---

background.js

In the field we saw multiple errors were the browser was not able to communicate with the host part. This usually is the case if a flatpak version of the browser is used or the host tooling simply was not installed. We now report this error via the tooltip of the disabled extension.

chore(ui): report broken connection to host tooling

---

README.md
background.js

The Firefox version of the extension also works in Thunderbird (without any modifications). By that, the device trust can also be added to tokens requested via OIDC for backends like IMAP, SMTP and EWS.
We add a note about this to the README.

docs: describe how to use the extension in thunderbird

---

linux-entra-sso.py

The Edge browser also sets the uxContextHandle and the ssoUrl in the authParameters object. We now also provide this data to be closer to the reference implementation.
This change does not affect the protocol between the webext and the native part.

feat: unify broker data with Edge

---

src/background.js

As the notify_state_change accesses the broker object to check if the connection is running, we also need to instantiate the broker first. Currently, the extension fails to load, as the broker object is null at this point in time. This obvious error looks like a rebase artifact, which was introduced in da8b99c.
Fixes: da8b99c ("refactor: move native messaging to separate module")

fix: notify state change only after broker is initialized

---

Makefile
PRIVACY.md
README.md
docs/global_install.md
platform/chrome/js/platform.js
platform/chrome/manifest.json
platform/chrome/storage-schema.json
platform/chrome/storage-schema.json.license
platform/firefox/js/platform.js
platform/firefox/manifest.json
platform/thunderbird/manifest.json
popup/menu.css
popup/menu.html
popup/menu.js
src/account.js
src/background.js
src/broker.js
src/platform-abstraction.js
src/policy.js
src/utils.js

These changes bring us closer to what the Edge browser is sending to the broker. We are still not fully there, but this is as far as I was able to deduce things from the official docs.
One parameter is missing, though. If someone has an idea where this data comes from (not always set), I'm happy to add it as well.
```json
"authParameters": { "requestOptions": [202, 205] }
```
Apart from that, we now support the silent token refresh of well-known apps. For that, the app URLs must be listed in the `host_permissions`. This is due to a requirement of the `webRequest` and `delarativeNetRequest` API that only operates on whitelisted URLs (the one in the browser bar), even if the `sub_frame` requests targets an already listed page.

improvements of broker protocol and silent token refresh

---

.pages/thunderbird/updates.json
platform/firefox/linux_entra_sso.json
platform/thunderbird/manifest.json

As told by Mozilla [1], we should use a distinct application id for the thunderbird version. This also gives us the chance to select a new application id in the now preferred format (@string instead of email) [2].
To keep the id similar to the previous one, we now use "@linux-entra-sso.tb". Note, that this id cannot be changed later on without creating a "new" extension entry.
[1] https://discourse.mozilla.org/t/listing-webextension-on-both-amo-and-addons-thunderbird-net/145536/3
[2] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

chore(thunderbird): set application id

---

.github/workflows/release.yml

We add the logic to release the Thunderbird version of the extension, similar to the Firefox version. Note, that the thunderbird addons store has slightly different requirements (e.g. no signing for self-distributed extensions, no API v5 support for uploading), so the process also looks slightly different.

Add CI infrastructure to release Thunderbird version
